-- Report-a-user / report-a-message: purely additive, backward-compatible
-- extension of the existing Report model. No existing column is altered,
-- nothing is made NOT NULL, no data is backfilled or destroyed.
--
-- targetType defaults to 'LISTING' so every pre-existing Report row (all
-- listing reports, the only kind that existed before this migration) keeps
-- its correct meaning with zero backfill required.
--
-- reportedUserId / messageId are nullable FKs with ON DELETE SET NULL,
-- mirroring the existing Report.listingId pattern -- deleting the reported
-- user or message must never delete the report record itself.
--
-- messageSnapshot freezes the reported message's body text at report time,
-- since messages are mutable with no edit/delete audit trail of their own.
--
-- NOTE: hand-authored, not generated by `prisma migrate dev` -- no live
-- database connection is available in this worktree (no .env/DATABASE_URL
-- present). This SQL is written to match exactly what
-- `prisma migrate diff` would generate for the corresponding schema.prisma
-- changes, following this repo's own established precedent for the same
-- situation (see prior migrations' commit history / ai/decisions.md).
-- It has NOT been verified by applying it to a live database and must be
-- confirmed with `prisma migrate diff --from-migrations ... --to-schema-datamodel
-- prisma/schema.prisma` (or an actual `prisma migrate dev`) against a real
-- database before this branch is deployed.

-- CreateEnum
CREATE TYPE "ReportTargetType" AS ENUM ('LISTING', 'USER', 'MESSAGE');

-- AlterTable
ALTER TABLE "Report" ADD COLUMN "targetType" "ReportTargetType" DEFAULT 'LISTING';
ALTER TABLE "Report" ADD COLUMN "reportedUserId" TEXT;
ALTER TABLE "Report" ADD COLUMN "messageId" TEXT;
ALTER TABLE "Report" ADD COLUMN "messageSnapshot" TEXT;

-- CreateIndex
CREATE INDEX "Report_targetType_idx" ON "Report"("targetType");

-- CreateIndex
CREATE INDEX "Report_reportedUserId_idx" ON "Report"("reportedUserId");

-- AddForeignKey
ALTER TABLE "Report" ADD CONSTRAINT "Report_reportedUserId_fkey" FOREIGN KEY ("reportedUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Report" ADD CONSTRAINT "Report_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "Message"("id") ON DELETE SET NULL ON UPDATE CASCADE;
