import { Metadata } from 'next';
import Link from 'next/link';
import PolicyLayout, { PolicySection } from '@/components/legal/PolicyLayout';

export const metadata: Metadata = { title: 'Privacy Policy' };

const sections: PolicySection[] = [
  {
    id: 'collect',
    heading: 'Information we collect',
    body: (
      <>
        <p>We collect the information you give us directly, and a small amount of information generated by using the Platform:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>Account information</strong> — name, email address, and password (we store a bcrypt hash, never your plain-text password), or, if you sign in with Google, the profile info Google shares with us (name, email, profile photo). Phone number and a short bio are optional.</li>
          <li><strong>Listing information</strong> — anything you include in a listing: description, price, address/location, photos, and any contact details you choose to add.</li>
          <li><strong>Messages</strong> — the content of messages you send through the Platform's messaging feature, and read/typing status.</li>
          <li><strong>Reports</strong> — if you report a listing, the reason and any description you provide.</li>
          <li><strong>Technical information</strong> — standard request logs (IP address, browser user agent, timestamps) generated automatically by our hosting infrastructure and used for security and rate-limiting.</li>
        </ul>
        <p>We don't use advertising or analytics tracking scripts, and we don't buy data about you from third parties.</p>
      </>
    ),
  },
  {
    id: 'use',
    heading: 'How we use your information',
    body: (
      <ul className="list-disc pl-5 space-y-1.5">
        <li>To operate the Platform — creating your account, showing your listings, connecting you with other users through messaging.</li>
        <li>To send account-related email, such as confirming a new sign-in method or an email change.</li>
        <li>To detect and prevent fraud, abuse, and violations of our <Link href="/terms" className="text-brand-700 hover:underline">Terms</Link> or <Link href="/community-guidelines" className="text-brand-700 hover:underline">Content &amp; Community Guidelines</Link>.</li>
        <li>To respond to reports and support requests.</li>
        <li>To comply with legal obligations, such as a valid request from a Canadian regulator or law enforcement.</li>
      </ul>
    ),
  },
  {
    id: 'visibility',
    heading: 'What other users can see',
    body: (
      <>
        <p>
          Some information you provide is public by design, because the Platform is a listing marketplace: your
          display name and profile photo are visible on your listings and in messages; a listing's description,
          price, location, photos, and, if you added one, its contact information are visible to any visitor to
          the site, including people who aren't signed in. Don't include information in a public listing that you
          don't want a stranger to see.
        </p>
        <p>Your email address and phone number are never shown publicly — only your listings and, if you send one, your messages are visible to the other user in that conversation.</p>
      </>
    ),
  },
  {
    id: 'location',
    heading: 'Location data',
    body: (
      <p>
        A listing's location (used to show it on the map) is the property address or neighbourhood you enter when
        posting it — we don't collect or track your device's GPS location, and we don't request location
        permissions in your browser.
      </p>
    ),
  },
  {
    id: 'cookies-storage',
    heading: 'Cookies and browser storage',
    body: (
      <>
        <p>
          We use one functional cookie to keep you signed in: a refresh token, set as HTTP-only (not readable by
          page scripts), marked Secure, and scoped to our authentication endpoint. It exists purely to keep your
          session alive — we don't set advertising or analytics cookies.
        </p>
        <p>
          Separately, your browser's local storage is used to hold your current session token and a copy of your
          basic profile info, so the app can recognize you without an extra request on every page load. Because
          this is regular browser storage rather than an HTTP-only cookie, it's a standard security tradeoff worth
          being aware of: it could in principle be read by malicious script if a script-injection vulnerability
          were ever found on the site. We apply a strict content-security policy and sanitize user input
          specifically to reduce that risk.
        </p>
      </>
    ),
  },
  {
    id: 'providers',
    heading: 'Service providers we use',
    body: (
      <>
        <p>We rely on a small number of infrastructure providers to run the Platform. Each processes data only as needed to provide their service to us, under their own privacy terms:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>Hosting</strong> — our website and API are hosted by third-party cloud platforms, and our database runs on a managed PostgreSQL provider.</li>
          <li><strong>File storage</strong> — listing photos and profile pictures are stored on S3-compatible object storage.</li>
          <li><strong>Google Sign-In</strong> — if you choose to sign in with Google, Google verifies your identity and shares your basic profile with us; we don't receive your Google password.</li>
          <li><strong>Email delivery</strong> — account-related emails (such as email-change confirmation) are sent through a transactional email provider when that feature is active.</li>
        </ul>
        <p>We don't sell or rent your personal information to anyone, for any purpose.</p>
      </>
    ),
  },
  {
    id: 'retention',
    heading: 'How long we keep your information',
    body: (
      <>
        <p>
          We keep your account and listing information for as long as your account is active, or as needed to
          operate the Platform and resolve any open reports or disputes. We don't currently run automated,
          scheduled deletion of old data on a fixed timeline — if that changes, we'll update this section.
        </p>
        <p>
          When you delete your account (see the next section), we deactivate it immediately and remove or
          anonymize your personal information as described below.
        </p>
      </>
    ),
  },
  {
    id: 'rights',
    heading: 'Your rights and choices',
    body: (
      <>
        <p>Canadian privacy law (including PIPEDA, where it applies) gives you rights over your personal information. On this Platform, you can exercise most of them yourself:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>Access and correction</strong> — view and update your name, phone, bio, and profile photo any time from Settings.</li>
          <li><strong>Delete your account</strong> — also available from Settings. This is irreversible. When you delete your account, we deactivate it, remove your listings from public view, delete your profile photo, and replace your name and email with a placeholder so you can no longer sign in. We keep the record of messages you sent in shared conversations rather than deleting them outright, since removing them would also destroy the other participant's conversation history — your name is replaced with "Deleted user" going forward.</li>
          <li><strong>Withdraw Google sign-in</strong> — you can revoke the Platform's access from your Google Account settings at any time; this doesn't delete your Muslim Rentals account, which you'd still need to delete separately if you want that.</li>
        </ul>
        <p>
          For anything you can't do yourself — for example, requesting a copy of your data in a specific format, or
          a question about how we've handled your information — contact us at{' '}
          <a href="mailto:support@muslimrentals.ca" className="text-brand-700 hover:underline">support@muslimrentals.ca</a>.
          You also have the right to complain to the{' '}
          <a href="https://www.priv.gc.ca" target="_blank" rel="noopener noreferrer" className="text-brand-700 hover:underline">
            Office of the Privacy Commissioner of Canada
          </a>{' '}
          if you believe we've mishandled your information.
        </p>
      </>
    ),
  },
  {
    id: 'children',
    heading: "Children's privacy",
    body: <p>The Platform is intended for users 18 and older, per our <Link href="/terms" className="text-brand-700 hover:underline">Terms</Link>. We don't knowingly collect information from anyone under 18.</p>,
  },
  {
    id: 'changes',
    heading: 'Changes to this policy',
    body: (
      <p>
        We may update this Privacy Policy as the Platform changes. We'll update the "Effective" date above when we
        do, and for a significant change, we'll try to give you notice through the Platform.
      </p>
    ),
  },
  {
    id: 'contact',
    heading: 'Contact us',
    body: (
      <p>
        Questions about this policy or your information can be sent to{' '}
        <a href="mailto:support@muslimrentals.ca" className="text-brand-700 hover:underline">support@muslimrentals.ca</a>{' '}
        or via our <Link href="/contact" className="text-brand-700 hover:underline">Contact page</Link>.
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <PolicyLayout
      title="Privacy Policy"
      effectiveDate="September 1, 2026"
      intro={
        <p>
          This policy explains what personal information Muslim Rentals collects, how we use it, who we share it
          with, and the choices and rights you have — written to describe what the Platform actually does, not a
          generic template.
        </p>
      }
      sections={sections}
    />
  );
}
